apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 10m
  chart:
    spec:
      chart: keycloak
      version: "25.2.0"   # pin a version
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    createNamespace: true
  values:
    auth:
      adminUser: admin
      adminPassword: admin
    service:
      type: ClusterIP
